# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: Usage
  items:
    - label: 'CartProvider'
      link: '/usage/cartprovider'
    - label: 'addItem()'
      link: '/usage/navigation'
    - label: 'Shadowing'
      link: '/usage/shadowing'
