# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: Usage
  items:
    - label: 'CartProvider'
      link: '/usage/cartprovider'
    - label: 'addItem()'
      link: '/usage/addItem()'
    - label: 'API'
      link: '/usage/api'
- label: 'Contributors'
  link: '/contributors'